export const PRIMARY_CATEGORIES = [
  { name: "Chicken", icon: "🐔" },
  { name: "Beef", icon: "🐂" },
  { name: "Pork", icon: "🐖" },
  { name: "Duck", icon: "🦆" },
  { name: "Lamb", icon: "🐑" },
  { name: "King Prawn", icon: "🦐" },
  { name: "Shrimp", icon: "🍤" },
  { name: "Fish", icon: "🐟" },
  { name: "Mushroom", icon: "🍄" },
  { name: "Veg", icon: "🥦" },
  { name: "Special", icon: "⭐" },
  { name: "Btn 1", icon: "1️⃣" },
  { name: "Btn 2", icon: "2️⃣" },
  { name: "Btn 3", icon: "3️⃣" },
  { name: "Rice", icon: "🍚" },
  { name: "Chips", icon: "🍟" },
];

export const SECONDARY_CATEGORY_PAGES = [
  [
    { zh: "全部", en: "Show All" },
    { zh: "头盘", en: "Starter" },
    { zh: "排骨", en: "Spare Rib" },
    { zh: "鸡翼", en: "Chicken Wing" },
    { zh: "汤", en: "Soup" },
    { zh: "椒盐", en: "Salt & Pepper" },
    { zh: "沙爹", en: "Satay" },
    { zh: "豉椒", en: "Black Bean" },
    { zh: "咖喱", en: "Curry" },
    { zh: "泰咖喱", en: "Thai-Curry" },
    { zh: "泰式", en: "Thai" },
    { zh: "三宝", en: "Sambal" },
    { zh: "特色", en: "Chef's" },
    { zh: "姜葱", en: "Ginger & S Onion" },
    { zh: "咕老", en: "Sweet & Sour" },
    { zh: "辣蒜", en: "Chilli Garlic" },
    { zh: "京式", en: "Peking" },
    { zh: "腰果", en: "Cashew Nuts" },
    { zh: "黑椒", en: "Black Pepper" },
    { zh: "柠檬/梅", en: "Lemon/Plum" },
    { zh: "菠萝", en: "Pineapple" },
    { zh: "宫保", en: "Kung Po" },
    { zh: "什水", en: "Chop Suey" },
    { zh: "什菜", en: "Mixed Veg" },
    { zh: "四川", en: "Szechuan" },
    { zh: "蚝油", en: "Oyster" },
    { zh: "毛菇", en: "Mushroom" },
    { zh: "饭", en: "Rice" },
    { zh: "面", en: "Chow Mein" },
    { zh: "斋", en: "Vegetarian" },
    { zh: "餐盒", en: "Snack Box" },
    { zh: "西餐", en: "English" },
    { zh: "芙蓉", en: "Foo Yung" },
    { zh: "<<", en: "<<" },
    { zh: ">>", en: ">>" },
  ],
  [
    { zh: "全部", en: "Show All" },
    { zh: "乌冬", en: "Udon" },
    { zh: "脆面", en: "Crispy Noodle" },
    { zh: "中式", en: "Chinese Style" },
    { zh: "蒜蓉", en: "Garlic Sauce" },
    { zh: "上海", en: "Shanghai Style" },
    { zh: "洋葱", en: "Onion" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "", en: "" },
    { zh: "<<", en: "<<" },
    { zh: ">>", en: ">>" },
  ],
];
