/**
 * domains/customers/customers.service.js
 *
 * Customer business rules. No Express types. No DB access. No hardware calls.
 *
 * Phase 1 implements:
 *  - getOrCreateCustomer(phone) — lookup or create, increment call count
 *  - updateCustomerAddress(phone, addressData) — validate and persist address fields
 *
 * Phase 2 stubs (require address API):
 *  - enrichCustomerAddress(phone, postcode)
 */

import { randomUUID } from "crypto";
import * as repo from "./customers.repo.js";
import * as orders from "../orders/orders.service.js";
import * as postcodes from "../../shared/postcodes.js";
import * as addressClient from "../callerIdService/addressClient.js";
import { haversineInMiles } from "../../shared/haversine.js";
import { config } from "../../config/index.js";
import { logger } from "../../infrastructure/logger.js";
import { ValidationError, NotFoundError } from "../../shared/errors.js";
import { normaliseUkPhone } from "../../shared/phones.js";

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Validate that a phone string looks like a plausible UK number.
 * This is a basic sanity check, not a full E.164 validator.
 * The old system accepted any string — we require at least 10 digits here.
 *
 * @param {string} phone
 * @throws {ValidationError}
 */
function validatePhone(phone) {
  if (!phone || typeof phone !== "string") {
    throw new ValidationError("Phone must be a non-empty string", { field: "phone" });
  }

  // Allow anonymous identifiers (generated by client or backend)
  if (phone.startsWith("UNKNOWN-")) {
    return phone;
  }

  const digits = normaliseUkPhone(phone);
  if (digits.length < 10 || digits.length > 13) {
    throw new ValidationError("Phone number must contain between 10 and 13 digits", {
      field: "phone",
      received: phone,
    });
  }
  return digits;
}

function isAnonymizedPhoneIdentifier(phone) {
  return typeof phone === "string" && phone.startsWith("ANON-");
}

// ---------------------------------------------------------------------------
// Business logic
// ---------------------------------------------------------------------------

export function getOrCreateCustomer(phone) {
  const normPhone = validatePhone(phone);
  return repo.upsertAndIncrementCallCount(normPhone, {});
}

/**
 * Update address fields for an existing customer.
 *
 * @param {string} phone
 * @param {object} addressData
 * @returns {object} Updated customer record
 * @throws {ValidationError} if phone is invalid
 * @throws {NotFoundError} if customer does not exist
 */
export function updateCustomerAddress(phone, addressData) {
  const normPhone = validatePhone(phone);

  const existing = repo.findByPhone(normPhone);
  if (!existing) {
    throw new NotFoundError(`Customer with phone ${phone} not found`, { phone });
  }

  repo.updateAddress(normPhone, addressData);
  return repo.findByPhone(normPhone);
}

/**
 * Find a customer by phone.
 *
 * @param {string} phone
 * @returns {object}
 * @throws {NotFoundError}
 */
export function getCustomerByPhone(phone) {
  const normPhone = validatePhone(phone);
  const customer = repo.findByPhone(normPhone);
  if (!customer) {
    throw new NotFoundError(`Customer with phone ${phone} not found`, { phone });
  }
  return customer;
}
/**
 * Update the master customer profile using information from an order.
 * This ensures the export/search records are always up to date.
 *
 * @param {object} customerInfo - The customerInfo blob from an order
 */
export function syncCustomerFromOrder(customerInfo) {
  if (!customerInfo?.phone) return;

  const phone = validatePhone(customerInfo.phone);
  const hasValidCoordinates =
    Number.isFinite(customerInfo.latitude) && Number.isFinite(customerInfo.longitude);
  const normalizedDistance = Number.isFinite(customerInfo.distance)
    ? Number(customerInfo.distance)
    : undefined;

  // We use the existing update logic to fill in/overwrite the profile
  // with the details from the most recent order.
  const data = {
    name: customerInfo.name,
    houseNumber: customerInfo.houseNumber,
    street: customerInfo.street,
    town: customerInfo.town,
    postcode: customerInfo.postcode,
    latitude: hasValidCoordinates ? Number(customerInfo.latitude) : undefined,
    longitude: hasValidCoordinates ? Number(customerInfo.longitude) : undefined,
    // Ignore placeholder distance values unless they are backed by coordinates.
    distance: hasValidCoordinates ? normalizedDistance : undefined,
  };

  // Ensure the customer exists first (upsert behavior)
  const existing = repo.findByPhone(phone);
  if (!existing) {
    repo.upsertCustomer({
      phone,
      ...data,
      firstCall: new Date().toISOString(),
      lastCall: new Date().toISOString(),
      callCount: 1,
    });
  } else {
    repo.updateAddress(phone, data);
    // Also update the name if it's provided in the order but missing in the profile
    if (customerInfo.name && (!existing.name || existing.name === "Anonymous Guest")) {
      repo.updateName(phone, customerInfo.name);
    }
  }
}

// ---------------------------------------------------------------------------
// Phase 2 stubs (require address API / postcode DB)
// ---------------------------------------------------------------------------

function toKnownAddressShape(address) {
  return {
    line1: address.line1 || "",
    line2: address.line2 || "",
    town: address.town || "",
    postcode: address.postcode || "",
    latitude: address.latitude,
    longitude: address.longitude,
    source: "customer_profile",
  };
}

function addressMatchesCustomerIdentity(customer, address) {
  const line1 = (address.line1 || address.street || "").trim().toLowerCase();
  const line2 = (address.line2 || "").trim().toLowerCase();
  const joined = `${line1} ${line2}`.trim();

  let hasIdentityAnchor = false;

  if (customer.houseNumber) {
    hasIdentityAnchor = true;
    const escaped = customer.houseNumber.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const houseNumberRe = new RegExp(`(^|\\s)${escaped}(\\s|,|$)`, "i");
    if (!houseNumberRe.test(line1)) return false;
  }

  if (customer.street) {
    hasIdentityAnchor = true;
    const expectedStreet = customer.street.trim().toLowerCase();
    if (!joined.includes(expectedStreet)) return false;
  }

  return hasIdentityAnchor;
}

function mapAddressRecord(addr, postcode) {
  return {
    line1: addr.line1 || addr.street || "",
    line2: addr.line2 || "",
    town: addr.town || addr.ward || "",
    postcode: addr.postcode || postcode,
    latitude: addr.latitude,
    longitude: addr.longitude,
    source: addr.source || "local_db",
  };
}

/**
 * Enrich a customer's address data using the local database and API fallback.
 *
 * Steps:
 *  1. Look up postcode in local DB.
 *  2. If not found, look up via getaddress.io API.
 *  3. If API succeeds, save results to local DB for future use.
 *  4. Calculate delivery distance from store to customer coordinates.
 *  5. Update the customer's cached distance and coordinate fields.
 *
 * @param {string} phone
 * @param {string} postcode
 * @returns {Promise<{ customer: object, addresses: Array<object> }>}
 */
export async function enrichCustomerAddress(phone, postcode) {
  const normPhone = validatePhone(phone);
  const normPostcode = postcodes.normalisePostcode(postcode);

  const customer = repo.findByPhone(normPhone);
  if (!customer) {
    throw new NotFoundError(`Customer with phone ${phone} not found`, { phone });
  }

  // Source of truth: customer-linked address history.
  const knownAddresses = repo.listAddressesByCustomer(normPhone);
  if (knownAddresses.length > 0) {
    const primary = knownAddresses[0];
    if (Number.isFinite(primary.latitude) && Number.isFinite(primary.longitude)) {
      const dist = haversineInMiles(
        config.address.storeLatitude,
        config.address.storeLongitude,
        primary.latitude,
        primary.longitude,
      );
      repo.updateAddress(normPhone, {
        postcode: primary.postcode,
        houseNumber: primary.houseNumber,
        street: primary.line1,
        town: primary.town,
        latitude: primary.latitude,
        longitude: primary.longitude,
        distance: parseFloat(dist.toFixed(2)),
      });
    }

    return {
      customer: repo.findByPhone(normPhone),
      addresses: knownAddresses.map(toKnownAddressShape),
    };
  }

  if (!normPostcode) {
    logger.info("Address enrichment skipped: customer has no postcode", { phone: normPhone });
    return { customer, addresses: [] };
  }

  let candidates = postcodes
    .findAddressesLocally(normPostcode)
    .map((addr) => mapAddressRecord(addr, normPostcode));

  if (candidates.length === 0) {
    const apiResults = await addressClient.findAddressesFromApi(normPostcode);
    if (apiResults && apiResults.length > 0) {
      candidates = apiResults.map((addr) => ({
        line1: addr.line1 || "",
        line2: addr.line2 || "",
        town: addr.town || "",
        postcode: normPostcode,
        latitude: addr.latitude,
        longitude: addr.longitude,
        source: "api",
      }));

      postcodes.saveAddresses(
        normPostcode,
        {
          street: candidates[0].line1,
          town: candidates[0].town,
          latitude: candidates[0].latitude,
          longitude: candidates[0].longitude,
        },
        candidates,
      );
    }
  }

  const matched = candidates.filter((addr) => addressMatchesCustomerIdentity(customer, addr));
  if (matched.length === 0) {
    logger.info("Address enrichment found postcode candidates but no customer-identity matches", {
      phone: normPhone,
      postcode: normPostcode,
      candidateCount: candidates.length,
    });
    return { customer, addresses: [] };
  }

  for (const addr of matched) {
    repo.upsertCustomerAddress(normPhone, {
      houseNumber: customer.houseNumber ?? undefined,
      line1: addr.line1,
      line2: addr.line2,
      town: addr.town,
      postcode: addr.postcode,
      latitude: addr.latitude,
      longitude: addr.longitude,
    });
  }

  const primary = matched[0];
  if (Number.isFinite(primary.latitude) && Number.isFinite(primary.longitude)) {
    const dist = haversineInMiles(
      config.address.storeLatitude,
      config.address.storeLongitude,
      primary.latitude,
      primary.longitude,
    );

    repo.updateAddress(normPhone, {
      postcode: primary.postcode,
      houseNumber: customer.houseNumber ?? undefined,
      street: primary.line1,
      town: primary.town,
      latitude: primary.latitude,
      longitude: primary.longitude,
      distance: parseFloat(dist.toFixed(2)),
    });
  }

  logger.debug("Customer address enriched using identity-linked matches", {
    phone: normPhone,
    postcode: normPostcode,
    matchedCount: matched.length,
  });

  return { customer: repo.findByPhone(normPhone), addresses: matched };
}

/**
 * Permanently delete a customer profile and anonymize their order history.
 * (GDPR Right to Erasure)
 *
 * @param {string} phone
 * @returns {{ ordersAnonymized: number }}
 */
export function deleteCustomerData(phone) {
  if (isAnonymizedPhoneIdentifier(phone)) {
    throw new ValidationError(
      "Customer record has already been anonymised and cannot be deleted again",
      { field: "phone", anonymised: true },
    );
  }

  const normPhone = validatePhone(phone);

  // 1. Generate an anonymization ID to link old orders without PII
  const anonId = `ANON-${randomUUID()}`;

  // 2. Scrub PII from the orders table
  const ordersAnonymized = orders.scrubOrdersByPhone(normPhone, anonId);

  // 3. Delete the customer profile
  repo.deleteByPhone(normPhone);

  logger.info("Customer data erased (GDPR)", {
    ordersAnonymized,
    piiRemoved: true,
  });

  return { ordersAnonymized };
}

/**
 * Gather all data stored about a customer.
 * (GDPR Right of Access)
 *
 * @param {string} phone
 * @returns {{ customer: object, orders: Array<object> }}
 */
export function exportCustomerData(phone) {
  if (isAnonymizedPhoneIdentifier(phone)) {
    throw new ValidationError("Customer record has been anonymised and can no longer be exported", {
      field: "phone",
      anonymised: true,
    });
  }

  const normPhone = validatePhone(phone);

  const customer = repo.findByPhone(normPhone);
  if (!customer) {
    throw new NotFoundError(`Customer with phone ${phone} not found`, { phone });
  }

  const history = orders.getOrdersByPhone(normPhone);

  return {
    customer,
    orders: history,
    exportedAt: new Date().toISOString(),
  };
}
