/**
 * domains/orders/orders.repo.js
 *
 * All SQL for the `orders` table. No business logic lives here.
 *
 * Rules:
 *  - JSON serialisation/deserialisation of the `data` column happens here ONLY.
 *  - IDs are generated by SQLite AUTOINCREMENT — never by the application.
 *  - No SQLite row objects or Statement instances are ever returned to callers.
 */

import { getDb } from "../../infrastructure/db.js";
import { AppError } from "../../shared/errors.js";

// ---------------------------------------------------------------------------
// Statement Cache
// ---------------------------------------------------------------------------

/**
 * Cache for prepared statements to avoid re-preparing on every call.
 * better-sqlite3 statements should be prepared once and reused.
 * @type {Object.<string, import('better-sqlite3').Statement>}
 */
const stmts = {
  insert: null,
  findById: null,
  findAll: null,
  findByDate: null,
  delete: null,
  deleteByDate: null,
  deleteBeforeDate: null,
  findByCustomerPhone: null,
};

/**
 * Ensures statements are prepared and returns the cache.
 * @returns {typeof stmts}
 */
function getStmts() {
  const db = getDb();
  if (!stmts.insert) {
    stmts.insert = db.prepare("INSERT INTO orders (data, archived_at) VALUES (?, ?)");
    stmts.findById = db.prepare("SELECT * FROM orders WHERE id = ?");
    stmts.findAll = db.prepare("SELECT * FROM orders ORDER BY archived_at DESC LIMIT 500");
    stmts.findByDate = db.prepare(
      "SELECT * FROM orders WHERE archived_at LIKE ? ORDER BY archived_at DESC",
    );
    stmts.delete = db.prepare("DELETE FROM orders WHERE id = ?");
    stmts.deleteByDate = db.prepare("DELETE FROM orders WHERE archived_at LIKE ?");
    stmts.deleteBeforeDate = db.prepare("DELETE FROM orders WHERE archived_at < ?");
    stmts.findByCustomerPhone = db.prepare(`
      SELECT id, data, archived_at
      FROM orders
      WHERE json_valid(data) = 1
        AND json_extract(data, '$.customerInfo.phone') = ?
      ORDER BY archived_at DESC
    `);
  }
  return stmts;
}

// ---------------------------------------------------------------------------
// Row → domain object mappers
// ---------------------------------------------------------------------------

/**
 * Map a raw SQLite row to a plain order object.
 * @param {object} row
 * @returns {object}
 */
function rowToOrder(row) {
  let data;
  try {
    data = JSON.parse(row.data);
  } catch (err) {
    throw new AppError(
      `Order ${row.id} has corrupted data and cannot be parsed`,
      "INTERNAL_ERROR",
      { id: row.id, error: err.message },
    );
  }

  return {
    id: row.id,
    data,
    archivedAt: row.archived_at,
  };
}

// ---------------------------------------------------------------------------
// Repository functions
// ---------------------------------------------------------------------------

/**
 * Insert a new order into the database.
 *
 * @param {{ data: object, archivedAt?: string }} orderData
 * @returns {{ id: number, data: object, archivedAt: string }}
 */
export function createOrder({ data, archivedAt }) {
  const { insert } = getStmts();
  const at = archivedAt ?? new Date().toISOString();

  // Use lastInsertRowid — never MAX(id)+1 — fixing the old race condition
  const result = insert.run(JSON.stringify(data), at);

  return {
    id: Number(result.lastInsertRowid),
    data,
    archivedAt: at,
  };
}

/**
 * Find a single order by its primary key.
 *
 * @param {number} id
 * @returns {{ id: number, data: object, archivedAt: string } | null}
 */
export function findOrderById(id) {
  const { findById } = getStmts();
  const row = findById.get(id);
  return row ? rowToOrder(row) : null;
}

/**
 * Return all archived orders, newest first.
 *
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findAllOrders() {
  const { findAll } = getStmts();
  const rows = findAll.all();
  return rows.map(rowToOrder);
}

/**
 * Return archived orders for a specific date (YYYY-MM-DD), newest first.
 *
 * @param {string} date - ISO date string (YYYY-MM-DD)
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findOrdersByDate(date) {
  const { findByDate } = getStmts();
  const rows = findByDate.all(`${date}%`);
  return rows.map(rowToOrder);
}

/**
 * Delete an order by ID.
 * The caller is responsible for verifying the order exists before calling this.
 *
 * @param {number} id
 * @returns {void}
 */
export function deleteOrder(id) {
  const { delete: delStmt } = getStmts();
  delStmt.run(id);
}

/**
 * Delete all orders for a specific date (YYYY-MM-DD).
 *
 * @param {string} date - ISO date string (YYYY-MM-DD)
 * @returns {void}
 */
export function deleteOrdersByDate(date) {
  const { deleteByDate } = getStmts();
  deleteByDate.run(`${date}%`);
}
/**
 * Delete all orders archived before a specific ISO 8601 timestamp.
 *
 * @param {string} date - ISO 8601 timestamp
 * @returns {number} Number of deleted rows
 */
export function deleteOrdersBefore(date) {
  const { deleteBeforeDate } = getStmts();
  const result = deleteBeforeDate.run(date);
  return result.changes;
}

/**
 * Find and anonymize all orders associated with a specific phone number.
 * Replaces customer PII with a unique anonymization ID.
 *
 * @param {string} phone - The phone number to scrub
 * @param {string} anonId - The UUID to use as a replacement
 * @returns {number} Number of orders anonymized
 */
export function anonymizeOrdersByPhone(phone, anonId) {
  const db = getDb();
  const { findByCustomerPhone } = getStmts();

  // Fast path: SQL-level exact phone match on JSON field.
  // Backed by idx_orders_customer_phone_json for large datasets.
  const candidateRows = findByCustomerPhone.all(phone);

  if (candidateRows.length === 0) return 0;

  const updateStmt = db.prepare("UPDATE orders SET data = ? WHERE id = ?");

  let count = 0;
  const anonymizeTx = db.transaction(() => {
    for (const row of candidateRows) {
      const data = JSON.parse(row.data);

      // Defensive exact-match check before scrubbing.
      if (data.customerInfo?.phone === phone) {
        // Scrub PII
        data.customerInfo = {
          name: "ANONYMISED",
          phone: anonId,
          address: "REMOVED",
          houseNumber: "REMOVED",
          street: "REMOVED",
          town: "REMOVED",
          postcode: "REMOVED",
          latitude: null,
          longitude: null,
          distance: null,
          mapRef: "REMOVED",
          deliveryInstructions: "REMOVED",
          deliveryTime: null,
          isAnonymised: true,
        };

        updateStmt.run(JSON.stringify(data), row.id);
        count++;
      }
    }
  });

  anonymizeTx();
  return count;
}

/**
 * Find all order history for a specific phone number.
 *
 * @param {string} phone
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findOrdersByPhone(phone) {
  const { findByCustomerPhone } = getStmts();
  const rows = findByCustomerPhone.all(phone);

  // Defensive parse + exact-match filter.
  return rows
    .map((row) => {
      try {
        const order = rowToOrder(row);
        if (order.data.customerInfo?.phone === phone) {
          return order;
        }
        return null;
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}
