/**
 * domains/orders/orders.repo.js
 *
 * All SQL for the `orders` table. No business logic lives here.
 *
 * Rules:
 *  - JSON serialisation/deserialisation of the `data` column happens here ONLY.
 *  - IDs are generated by SQLite AUTOINCREMENT — never by the application.
 *  - No SQLite row objects or Statement instances are ever returned to callers.
 */

import { getDb } from "../../infrastructure/db.js";
import { AppError } from "../../shared/errors.js";

// ---------------------------------------------------------------------------
// Statement Cache
// ---------------------------------------------------------------------------

/**
 * Cache for prepared statements to avoid re-preparing on every call.
 * better-sqlite3 statements should be prepared once and reused.
 * @type {Object.<string, import('better-sqlite3').Statement>}
 */
const stmts = {
  insert: null,
  findById: null,
  findByClientOrderId: null,
  findAll: null,
  findByDate: null,
  delete: null,
  deleteByDate: null,
  deleteBeforeDate: null,
  deleteStatus: null,
  deleteStatusByDate: null,
  deleteStatusBeforeDate: null,
  findByCustomerPhone: null,
  // kitchen screen
  initStatus: null,
  setStatus: null,
  getActive: null,
  getPrevStatus: null,
  getEtaData: null,
};

/**
 * Ensures statements are prepared and returns the cache.
 * @returns {typeof stmts}
 */
function getStmts() {
  const db = getDb();
  if (!stmts.insert) {
    stmts.insert = db.prepare("INSERT INTO orders (data, archived_at, client_order_id) VALUES (?, ?, ?)");
    stmts.findById = db.prepare("SELECT * FROM orders WHERE id = ?");
    stmts.findByClientOrderId = db.prepare("SELECT * FROM orders WHERE client_order_id = ?");
    stmts.findAll = db.prepare("SELECT * FROM orders ORDER BY archived_at DESC LIMIT 500");
    stmts.findByDate = db.prepare(
      "SELECT * FROM orders WHERE archived_at LIKE ? ORDER BY archived_at DESC",
    );
    stmts.delete = db.prepare("DELETE FROM orders WHERE id = ?");
    stmts.deleteByDate = db.prepare("DELETE FROM orders WHERE archived_at LIKE ?");
    stmts.deleteBeforeDate = db.prepare("DELETE FROM orders WHERE archived_at < ?");
    stmts.deleteStatus = db.prepare("DELETE FROM order_status WHERE order_id = ?");
    stmts.deleteStatusByDate = db.prepare(`
      DELETE FROM order_status
      WHERE order_id IN (SELECT id FROM orders WHERE archived_at LIKE ?)
    `);
    stmts.deleteStatusBeforeDate = db.prepare(`
      DELETE FROM order_status
      WHERE order_id IN (SELECT id FROM orders WHERE archived_at < ?)
    `);
    stmts.findByCustomerPhone = db.prepare(`
      SELECT id, data, archived_at
      FROM orders
      WHERE json_valid(data) = 1
        AND json_extract(data, '$.customerInfo.phone') = ?
      ORDER BY archived_at DESC
    `);
    // kitchen screen statements
    stmts.initStatus = db.prepare(`
      INSERT INTO order_status
        (order_id, status, estimated_ready_at, item_count, complexity, queue_depth, is_delivery, predicted_mins)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);
    stmts.setStatus = db.prepare(`
      UPDATE order_status
      SET status     = $status,
          updated_at = datetime('now'),
          updated_by = $updatedBy,
          actual_ready_at = CASE
            WHEN $status IN ('ready', 'complete') AND actual_ready_at IS NULL
            THEN datetime('now')
            ELSE actual_ready_at
          END
      WHERE order_id = $orderId
    `);
    stmts.getEtaData = db.prepare(`
      SELECT s.item_count, s.complexity, s.queue_depth, s.is_delivery,
             s.actual_ready_at, o.archived_at
      FROM order_status s
      JOIN orders o ON o.id = s.order_id
      WHERE s.order_id = ?
    `);
    stmts.getActive = db.prepare(`
      SELECT o.id, o.data, o.archived_at,
             s.status, s.updated_at, s.estimated_ready_at, s.actual_ready_at
      FROM orders o
      JOIN order_status s ON s.order_id = o.id
      WHERE s.status NOT IN ('complete', 'cancelled')
      ORDER BY o.archived_at ASC
    `);
    stmts.getPrevStatus = db.prepare(
      "SELECT status FROM order_status WHERE order_id = ?",
    );
  }
  return stmts;
}

// ---------------------------------------------------------------------------
// Row → domain object mappers
// ---------------------------------------------------------------------------

/**
 * Map a raw SQLite row to a plain order object.
 * @param {object} row
 * @returns {object}
 */
function rowToOrder(row) {
  let data;
  try {
    data = JSON.parse(row.data);
  } catch (err) {
    throw new AppError(
      `Order ${row.id} has corrupted data and cannot be parsed`,
      "INTERNAL_ERROR",
      { id: row.id, error: err.message },
    );
  }

  return {
    id: row.id,
    data,
    archivedAt: row.archived_at,
  };
}

// ---------------------------------------------------------------------------
// Repository functions
// ---------------------------------------------------------------------------

/**
 * Insert a new order into the database.
 *
 * @param {{ data: object, archivedAt?: string }} orderData
 * @returns {{ id: number, data: object, archivedAt: string }}
 */
export function createOrder({ data, archivedAt, clientOrderId }) {
  const { insert, findByClientOrderId } = getStmts();
  const at = archivedAt ?? new Date().toISOString();

  try {
    // Use lastInsertRowid — never MAX(id)+1 — fixing the old race condition
    const result = insert.run(JSON.stringify(data), at, clientOrderId ?? null);
    return { id: Number(result.lastInsertRowid), data, archivedAt: at };
  } catch (err) {
    // A duplicate clientOrderId means the client is retrying a request we already stored.
    // Return the original row so the response is idempotent.
    if (err.code === "SQLITE_CONSTRAINT_UNIQUE" && clientOrderId) {
      const existing = findByClientOrderId.get(clientOrderId);
      if (existing) return rowToOrder(existing);
    }
    throw err;
  }
}

/**
 * Find a single order by its primary key.
 *
 * @param {number} id
 * @returns {{ id: number, data: object, archivedAt: string } | null}
 */
export function findOrderById(id) {
  const { findById } = getStmts();
  const row = findById.get(id);
  return row ? rowToOrder(row) : null;
}

/**
 * Return all archived orders, newest first.
 *
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findAllOrders() {
  const { findAll } = getStmts();
  const rows = findAll.all();
  return rows.map(rowToOrder);
}

/**
 * Return archived orders for a specific date (YYYY-MM-DD), newest first.
 *
 * @param {string} date - ISO date string (YYYY-MM-DD)
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findOrdersByDate(date) {
  const { findByDate } = getStmts();
  const rows = findByDate.all(`${date}%`);
  return rows.map(rowToOrder);
}

/**
 * Delete an order by ID.
 * The caller is responsible for verifying the order exists before calling this.
 *
 * @param {number} id
 * @returns {void}
 */
export function deleteOrder(id) {
  const db = getDb();
  const { delete: delStmt, deleteStatus } = getStmts();
  db.transaction(() => {
    deleteStatus.run(id);
    delStmt.run(id);
  })();
}

/**
 * Delete all orders for a specific date (YYYY-MM-DD).
 *
 * @param {string} date - ISO date string (YYYY-MM-DD)
 * @returns {void}
 */
export function deleteOrdersByDate(date) {
  const db = getDb();
  const { deleteByDate, deleteStatusByDate } = getStmts();
  const pattern = `${date}%`;
  db.transaction(() => {
    deleteStatusByDate.run(pattern);
    deleteByDate.run(pattern);
  })();
}
/**
 * Delete all orders archived before a specific ISO 8601 timestamp.
 *
 * @param {string} date - ISO 8601 timestamp
 * @returns {number} Number of deleted rows
 */
export function deleteOrdersBefore(date) {
  const db = getDb();
  const { deleteBeforeDate, deleteStatusBeforeDate } = getStmts();
  return db.transaction(() => {
    deleteStatusBeforeDate.run(date);
    return deleteBeforeDate.run(date).changes;
  })();
}

/**
 * Find and anonymize all orders associated with a specific phone number.
 * Replaces customer PII with a unique anonymization ID.
 *
 * @param {string} phone - The phone number to scrub
 * @param {string} anonId - The UUID to use as a replacement
 * @returns {number} Number of orders anonymized
 */
export function anonymizeOrdersByPhone(phone, anonId) {
  const db = getDb();
  const { findByCustomerPhone } = getStmts();

  // Fast path: SQL-level exact phone match on JSON field.
  // Backed by idx_orders_customer_phone_json for large datasets.
  const candidateRows = findByCustomerPhone.all(phone);

  if (candidateRows.length === 0) return 0;

  const updateStmt = db.prepare("UPDATE orders SET data = ? WHERE id = ?");

  let count = 0;
  const anonymizeTx = db.transaction(() => {
    for (const row of candidateRows) {
      const data = JSON.parse(row.data);

      // Defensive exact-match check before scrubbing.
      if (data.customerInfo?.phone === phone) {
        // Scrub PII
        data.customerInfo = {
          name: "ANONYMISED",
          phone: anonId,
          address: "REMOVED",
          houseNumber: "REMOVED",
          street: "REMOVED",
          town: "REMOVED",
          postcode: "REMOVED",
          latitude: null,
          longitude: null,
          distance: null,
          mapRef: "REMOVED",
          deliveryInstructions: "REMOVED",
          deliveryTime: null,
          isAnonymised: true,
        };

        updateStmt.run(JSON.stringify(data), row.id);
        count++;
      }
    }
  });

  anonymizeTx();
  return count;
}

/**
 * Find all order history for a specific phone number.
 *
 * @param {string} phone
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findOrdersByPhone(phone) {
  const { findByCustomerPhone } = getStmts();
  const rows = findByCustomerPhone.all(phone);

  // Defensive parse + exact-match filter.
  return rows
    .map((row) => {
      try {
        const order = rowToOrder(row);
        if (order.data.customerInfo?.phone === phone) {
          return order;
        }
        return null;
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

// ---------------------------------------------------------------------------
// Kitchen screen — order_status table
// ---------------------------------------------------------------------------

/**
 * Insert an initial status row for a newly archived order.
 *
 * @param {number} orderId
 * @param {'new'|'cooking'} initialStatus
 * @param {string|null} estimatedReadyAt - ISO string from the RLS model
 * @param {{ itemCount: number, complexity: number, queueDepth: number, isDelivery: boolean, predictedMins: number }|null} etaData
 */
export function initOrderStatus(orderId, initialStatus = "new", estimatedReadyAt = null, etaData = null) {
  const { initStatus } = getStmts();
  initStatus.run(
    orderId,
    initialStatus,
    estimatedReadyAt,
    etaData?.itemCount ?? null,
    etaData?.complexity ?? null,
    etaData?.queueDepth ?? null,
    etaData?.isDelivery ? 1 : (etaData ? 0 : null),
    etaData?.predictedMins ?? null,
  );
}

/**
 * Return the stored ETA feature data and timing for a completed order.
 * Used to trigger the RLS model update.
 *
 * @param {number} orderId
 * @returns {{ itemCount: number, complexity: number, queueDepth: number, isDelivery: boolean, actualReadyAt: string|null, archivedAt: string }|null}
 */
export function getOrderEtaData(orderId) {
  const { getEtaData } = getStmts();
  const row = getEtaData.get(orderId);
  if (!row) return null;
  return {
    itemCount: row.item_count,
    complexity: row.complexity,
    queueDepth: row.queue_depth,
    isDelivery: row.is_delivery === 1,
    actualReadyAt: row.actual_ready_at ?? null,
    archivedAt: row.archived_at,
  };
}

/**
 * Transition an order to a new status.
 * Automatically sets actual_ready_at when status becomes 'ready'.
 *
 * @param {number} orderId
 * @param {string} status
 * @param {string} [updatedBy]
 */
export function setOrderStatus(orderId, status, updatedBy = "kitchen") {
  const { setStatus } = getStmts();
  setStatus.run({ status, updatedBy, orderId });
}

/**
 * Return all active orders (status not 'complete' or 'cancelled'), oldest first.
 *
 * @returns {Array<{
 *   orderId: number,
 *   order: object,
 *   status: string,
 *   archivedAt: string,
 *   updatedAt: string,
 *   estimatedReadyAt: string|null,
 *   actualReadyAt: string|null,
 * }>}
 */
export function getActiveOrders() {
  const { getActive } = getStmts();
  const rows = getActive.all();
  return rows.map((row) => {
    let order;
    try {
      order = JSON.parse(row.data);
    } catch {
      order = {};
    }
    return {
      orderId: row.id,
      order,
      status: row.status,
      archivedAt: row.archived_at,
      updatedAt: row.updated_at,
      estimatedReadyAt: row.estimated_ready_at ?? null,
      actualReadyAt: row.actual_ready_at ?? null,
    };
  });
}

/**
 * Return the current status of an order before updating it.
 * Used to capture previousStatus for the WS event.
 *
 * @param {number} orderId
 * @returns {string|null}
 */
export function getPreviousStatus(orderId) {
  const { getPrevStatus } = getStmts();
  const row = getPrevStatus.get(orderId);
  return row?.status ?? null;
}
