/**
 * domains/orders/orders.repo.js
 *
 * All SQL for the `orders` table. No business logic lives here.
 *
 * Rules:
 *  - JSON serialisation/deserialisation of the `data` column happens here ONLY.
 *  - IDs are generated by SQLite AUTOINCREMENT — never by the application.
 *  - No SQLite row objects or Statement instances are ever returned to callers.
 */

import { getDb } from '../../infrastructure/db.js';
import { AppError } from '../../shared/errors.js';

// ---------------------------------------------------------------------------
// Statement Cache
// ---------------------------------------------------------------------------

/**
 * Cache for prepared statements to avoid re-preparing on every call.
 * better-sqlite3 statements should be prepared once and reused.
 * @type {Object.<string, import('better-sqlite3').Statement>}
 */
const stmts = {
  insert: null,
  findById: null,
  findAll: null,
  findByDate: null,
  delete: null,
  deleteByDate: null,
};

/**
 * Ensures statements are prepared and returns the cache.
 * @returns {typeof stmts}
 */
function getStmts() {
  const db = getDb();
  if (!stmts.insert) {
    stmts.insert = db.prepare('INSERT INTO orders (data, archived_at) VALUES (?, ?)');
    stmts.findById = db.prepare('SELECT * FROM orders WHERE id = ?');
    stmts.findAll = db.prepare('SELECT * FROM orders ORDER BY archived_at DESC LIMIT 500');
    stmts.findByDate = db.prepare(
      'SELECT * FROM orders WHERE archived_at LIKE ? ORDER BY archived_at DESC',
    );
    stmts.delete = db.prepare('DELETE FROM orders WHERE id = ?');
    stmts.deleteByDate = db.prepare('DELETE FROM orders WHERE archived_at LIKE ?');
  }
  return stmts;
}

// ---------------------------------------------------------------------------
// Row → domain object mappers
// ---------------------------------------------------------------------------

/**
 * Map a raw SQLite row to a plain order object.
 * @param {object} row
 * @returns {object}
 */
function rowToOrder(row) {
  let data;
  try {
    data = JSON.parse(row.data);
  } catch (err) {
    throw new AppError(
      `Order ${row.id} has corrupted data and cannot be parsed`,
      'INTERNAL_ERROR',
      { id: row.id, error: err.message },
    );
  }

  return {
    id: row.id,
    data,
    archivedAt: row.archived_at,
  };
}

// ---------------------------------------------------------------------------
// Repository functions
// ---------------------------------------------------------------------------

/**
 * Insert a new order into the database.
 *
 * @param {{ data: object, archivedAt?: string }} orderData
 * @returns {{ id: number, data: object, archivedAt: string }}
 */
export function createOrder({ data, archivedAt }) {
  const { insert } = getStmts();
  const at = archivedAt ?? new Date().toISOString();

  // Use lastInsertRowid — never MAX(id)+1 — fixing the old race condition
  const result = insert.run(JSON.stringify(data), at);

  return {
    id: Number(result.lastInsertRowid),
    data,
    archivedAt: at,
  };
}

/**
 * Find a single order by its primary key.
 *
 * @param {number} id
 * @returns {{ id: number, data: object, archivedAt: string } | null}
 */
export function findOrderById(id) {
  const { findById } = getStmts();
  const row = findById.get(id);
  return row ? rowToOrder(row) : null;
}

/**
 * Return all archived orders, newest first.
 *
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findAllOrders() {
  const { findAll } = getStmts();
  const rows = findAll.all();
  return rows.map(rowToOrder);
}

/**
 * Return archived orders for a specific date (YYYY-MM-DD), newest first.
 *
 * @param {string} date - ISO date string (YYYY-MM-DD)
 * @returns {Array<{ id: number, data: object, archivedAt: string }>}
 */
export function findOrdersByDate(date) {
  const { findByDate } = getStmts();
  const rows = findByDate.all(`${date}%`);
  return rows.map(rowToOrder);
}

/**
 * Delete an order by ID.
 * The caller is responsible for verifying the order exists before calling this.
 *
 * @param {number} id
 * @returns {void}
 */
export function deleteOrder(id) {
  const { delete: delStmt } = getStmts();
  delStmt.run(id);
}

/**
 * Delete all orders for a specific date (YYYY-MM-DD).
 *
 * @param {string} date - ISO date string (YYYY-MM-DD)
 * @returns {void}
 */
export function deleteOrdersByDate(date) {
  const { deleteByDate } = getStmts();
  deleteByDate.run(`${date}%`);
}
